databases:
  - name: budget-app
    databaseName: budget_app_tb9o
    user: budget_app_tb9o_user

services:
  - type: web
    name: rails-budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false